doc/configuration.rst

The config-param name is changed downstream. This doc references it for completeness.

fixed doc to match mmnormalize module-load time config-param allowRegex

---

doc/configuration.rst
rulebases/sample.rulebase
rulebases/syntax.txt
src/parser.c
src/parser.h
src/samp.c

parse a sequence of strictly alphabetic characters.
allows to parse sequences like 'host451' with a rule like %base:alpha%%index:number%

add Alpha field parser

---

.gitignore
configure.ac
doc/configuration.rst
src/json_compatibility.c
src/json_compatibility.h
src/liblognorm.h
src/parser.c
src/parser.h
src/ptree.c
src/ptree.h
src/samp.c
src/samp.h
tests/.gitignore
tests/Makefile.am
tests/exec.sh
tests/field_descent.sh
tests/field_descent_with_invalid_ruledef.sh
tests/field_interpret.sh
tests/field_interpret_with_invalid_ruledef.sh
tests/field_recursive.sh
tests/field_tokenized.sh
tests/field_tokenized_recursive.sh
tests/field_tokenized_with_invalid_ruledef.sh
tests/json_eq.c

Summary:
- support for 'recursive' field (which calls the ruleset again to match a portion of string)
- support for returning unmatched-suffix fragment using 'tail'(or a configurable name, 'tail' being the default)
- support for type interpretation of field's matched values (via a type called 'interpret'), which supports int, base16-int, double and boolean as of now.
- support for 'descent' field (which is like recursive, but allows calling into a child rulebase). User can specify the file to be used as rulebase, but works similar to recursive.
- a utility(pcons_args function and sisters) for consuming field-declaration arguments, to make consuming optional arguments and generating error messages easier

Recursive field support + type-interpretation support

---

doc/configuration.rst
src/parser.c
src/parser.h
src/samp.c

op-quoted-string:
Basically just making an additional one like quoted string that does a quoted string if the first character is ", and does word matching otherwise.
to-string:
Matching up to a string. Copied the char-to function, then modified to check for the rest of the string after the first character matches. I believe this doesn't work with hex characters (so no \x20 and such) but it removes the need for using the regex function a good amount of the time
Bugfix:
Alpha (in the docs) didn't have the correct number of "#" under it. Fixed.

Adding op-quoted-string, to-string, and bugfix on docs.

---

.travis.yml

To make sure it compiles.
I don't have --enable-valgrind as that'll require more packages to be "apt-get" installed on travis.

Added --enable-docs to travis

---

.travis.yml
configure.ac
doc/configuration.rst
src/json_compatibility.c
src/json_compatibility.h
src/lognormalizer.c
src/parser.c
src/parser.h
src/samp.c
tests/Makefile.am
tests/field_float.sh
tests/field_float_with_invalid_ruledef.sh
tests/field_interpret.sh
tests/field_suffixed.sh
tests/field_suffixed_with_invalid_ruledef.sh
tests/field_tokenized.sh
tests/json_eq.c

- Implemented float (a type that parses real numbers in form of nnn.nnn) (note that this doesn't handle n.nnne^nn or any other scientific notation, but then those are not all that common in logs)
- Implemented suffixed and named_suffixed field types that allow parsing of fields that have one of many potential suffixes (like a disk-space value which may have suffix kb, mb, gb etc). Field named_suffixed does exactly the same thing as suffixed, but allows user to name the parsed-value and suffix field unlike suffixed, which provides default names "value" and "suffix".
- Tokenized wasn't working with lognorm special characters ('%' and ':') because it wasn't unescaping token-string, which is now fixed.

Support for float, suffixed-fields and a bug-fix to tokenized

---

tests/field_interpret.sh
tests/json_eq.c

json-c-0.12 has changed implementation of json_object_double_to_json_string. This was causing interpret unit failure.
Also change equality test for double from direct comparison to standard floating point comparison by checking difference to a error limit.

Changed double comparison in json eq. Fixed unit test of interpret

---

ChangeLog
src/parser.c

this was caused by inconsistencies between various macros. We have
changed the parser-generation macros to match the semantics of the
broader CHKN/CHKR macros and also restructured/simplified the
parser generation macros.
closes https://github.com/rsyslog/liblognorm/issues/41

some parsers did incorrectly report success when an error occurred

---

ChangeLog
doc/configuration.rst
src/parser.c
src/ptree.c
tests/Makefile.am
tests/field_rest.sh

Versions prior to 1.1.2 did execute "rest" during regular parser processing, and thus parser matches have been more or less random. With 1.1.2 this is now always the last parser called. This may cause problems with existing rulesets, HOWEVER, adding any other rule or changing the load order would also have caused problems, so there really is no compatibility to preserve.

call "rest" parser only if nothing else matches.

---

ChangeLog
configure.ac
src/parser.c
src/parser.h
src/samp.c
tests/Makefile.am
tests/field_name_value.sh

This merges the current state. It is useful as is, but it will improve. Still, it's time to merge, especially as part of the functionality can be used to support CEF (https://github.com/rsyslog/liblognorm/issues/40). After the merge, this is flagged as "officially unsupported/experimental" with the desire to change that with later commits.

Add parser for name/value pairs

---

Makefile.am
compat/Makefile.am
compat/strndup.c
configure.ac
src/Makefile.am
src/liblognorm.h
tests/Makefile.am

Fixes build problems in systems who do not have strndup support.
closes https://github.com/rsyslog/liblognorm/issues/100

Added strndup workaround from rsyslog into liblognorm.

---

src/v1_ptree.c

closes https://github.com/rsyslog/liblognorm/issues/127

nit: remove left-over debug aid

---

src/samp.c
tests/Makefile.am
tests/missing_line_ending.rb
tests/missing_line_ending.sh

This problem occurs with the very last line of a rulebase (at EOF).
If it is not properly terminated (LF missing), it is silently ignored.
Previous versions did obviously process lines in this case. While
technically this is invalid input, we can't outrule that such rulebases
exist. For example, they do in the rsyslog testbench, which made
us aware of the problem (see https://github.com/rsyslog/rsyslog/issues/489 ).
I think the proper way of addressing this is to process such lines without
termination, as many other tools do as well.
closes https://github.com/rsyslog/liblognorm/issues/135

"fix": process last line if it misses the terminating LF

---

ChangeLog
doc/configuration.rst
src/samp.c

for v1,
closes  https://github.com/rsyslog/liblognorm/issues/129

backport runaway rule check from v2

---

tests/exec.sh

do not use non-supported "local" sh keyword
closes https://github.com/rsyslog/liblognorm/issues/147

testbench: make work (better) on solaris

---

src/enc_syslog.c
src/enc_xml.c
src/parser.c
src/pdag.c
src/samp.c
tests/json_eq.c

they use internal implementation details; use _iter_ functions instead.
This is also necessary because libfastjson 0.99.3+ will no longer
support the foreach macros.
closes https://github.com/rsyslog/liblognorm/issues/197

v2: stop using foreach macros

---

.travis.yml
src/enc_syslog.c
src/enc_xml.c
tests/json_eq.c
tests/missing_line_ending.sh

they use internal implementation details; use _iter_ functions instead.
This is also necessary because libfastjson 0.99.3+ will no longer
support the foreach macros.
closes https://github.com/rsyslog/liblognorm/issues/196

v1: stop using foreach macros

---

.gitignore
src/lognormalizer.c
tests/Makefile.am
tests/very_long_logline.sh
tests/very_long_logline_jsoncnf.sh

This caused confusion with users trying to parse and seeing it fail and then assuming mmnormalize call will fail too.

lognormalizer now handles log-lines bigger than 10k

---

src/internal.h
src/liblognorm.h

This function is only used internally, so define it in internal.h.
Making it public breaks code which tries to build against liblognorm.h
due to conflicting definitions of strndup().
Since we already have an internal header file, just add the compat definitions there instead of creating a separate header file.
See #214

Do not define strndup() as part of the public API

---

src/v1_samp.c

v1_samp.c had mixed tabs and spaces indentation which GCC 6 complains
about:
v1_samp.c: In function 'ln_v1_processSamp':
v1_samp.c:764:5: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
if(getLineType(buf, lenBuf, &offs, &typeStr) != 0)
^~
v1_samp.c:767:2: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'if'
if(!es_strconstcmp(typeStr, "prefix")) {
^~
Fix by using tabs consistently in that function.

fix misleading indentation warnings with GCC6

---

src/lognormalizer.c
src/parser.c
src/v1_parser.c

Use type int instead of char in various places to fix GCC warning:
```
warning: comparison is always false due to limited range of data type [-Wtype-limits]
```
In case of lognormalizer using the incorrect type lead to a never finishing loop in read_line()

Type fixes

---

configure.ac
lognorm.pc.in

Requires.private has an unfortunate side effect: when pkg-config
--cflags is called, if the pkg-config of a Requires.private library
is not available, it will fail. This is very counter-intuitive, as
one would expect Requires.private to be parsed only if pkg-config is
called with --static, but that's the case only for --libs, not
--cflags.
Autogenerate Libs.private from libestr pkg-config --libs output via
autoconf.
Without libestr-dev installed (no libestr.pc):
```
$ PKG_CONFIG_PATH=./ pkg-config --static --libs lognorm
-L/usr/local/lib -llognorm -lestr -lfastjson 
$ PKG_CONFIG_PATH=./ pkg-config --libs lognorm
-L/usr/local/lib -llognorm -lfastjson 
$ PKG_CONFIG_PATH=./ pkg-config --cflags lognorm
-I/usr/local/include -I/usr/include/libfastjson 
```

Use Libs.private instead of Requires.private in pkgconfig

---

src/annot.c
src/samp.c

closes https://github.com/rsyslog/liblognorm/issues/224

bugfix: no error message emitted for invalid "annotate" operation

---

src/pdag.c
tests/Makefile.am
tests/literal.sh

if
rule=:%{"type":"literal", "text":"a", "name":"var"}%
is used and matching message is provided, variable var ist not persisted.
see also http://lists.adiscon.net/pipermail/rsyslog/2016-December/043985.html

bugfix: literal parser does not always store value if name is specified

---

src/parser.c
tests/Makefile.am
tests/rule_last_str_long.sh
tests/rule_last_str_short.sh

string parser will fail if it is the last thing on a line.
closes https://github.com/rsyslog/liblognorm/issues/207

bugfix: string parser mishandling strings at the end of rules

---

src/v1_ptree.c

Generates compiler warnins on some platforms and as such causes
CI to fail. Also, obviously not a good thing to have.

remove execessive use of "inline"

---

src/v1_parser.c

Free for es_str2cstr in ln_parseStringTo(PARSER(StringTo)) missing.

es_str2cstr leak in string-to v1 parse

---

doc/configuration.rst

Explicitly list supported whitespace characters

---

doc/lognormalizer.rst

This corrects the output CLI option from `-o` (which is for something else) to `-e` in the documentation.

Correct CLI options in the docs

---

src/internal.h
src/samp.c

The jump-misses-init gcc warning is overdoing when we jump to the
exit of a function to get proper finalization. So let's disable it.
This also fixes our Travis CI builds.

build system: fix gcc warning

---

src/parser.c

this could only happen if the system was totally out of memory
detected by Coverity Scan, CID 269248, 269247

fix potential NULL pointer addressing

---

src/pdag.c
src/pdag.h
tests/Makefile.am
tests/usrdef_nested_segfault.sh

The problem occurs when a user type references another user type : a pointer to the first type is stored in the second, but the array is realloc-ed when you add a third user type, and the pointer becomes invalid.
See issue for more details
1st commit for the test case
2nd will be the fix: use an index instead of a pointer

Fix for use after free (issue #235)

---

src/parser.c

Suppress invalid param error for name to fix #270 for hexnumber, float, number, date-rfc3164 and date-rfc5424.
It will just check if name is "-" to make sure that we only suppress the error message in case we do not want to capture something.

Suppress invalid param error for name to fix #270

---

src/lognorm.c

This should not happen due to the shortness of OS error
messages. Nevertheless, it does not hurt doing it right ;-)

fix very theoretic misadressing (gcc-8 warning)

---

src/samp.c

If a json rule used a LF inside a string rule (one not loaded
rulebase file), liblognorm segfaults.
closes https://github.com/rsyslog/liblognorm/issues/333

string rulebase bugfix: segfault when using LF in json rule

---

src/parser.c
tests/field_cef.sh
tests/field_cef_jsoncnf.sh

- When it encounters an escaped slash ( \\/ ) in the middle of a value
- When the last value is empty
This is particularly problematic for us as we have a lot of data in this format to parse.
- Log
```log
CEF:0|nxlog.org|nxlog|2.7.1243|Executable Code was Detected|Advanced exploit detected|100|path=Some\/Path spt=46117 dst=172.25.212.204 dpt=
```
- Rulebase
```
version=2
rule=%.:cef%
```
- Expected behavior
```json
{
"DeviceVendor": "nxlog.org",
"DeviceProduct": "nxlog",
"DeviceVersion": "2.7.1243",
"SignatureID": "Executable Code was Detected",
"Name": "Advanced exploit detected",
"Severity": "100",
"Extensions": {
"path": "Some/Path",
"spt": "46117",
"dst": "172.25.212.204",
"dpt": ""
}
}
```
- Current behavior
```json
{
"originalmsg": "CEF:0|nxlog.org|nxlog|2.7.1243|Executable Code was …
```

FIX CEF PARSER

---

README
doc/conf.py
doc/index.rst

I would like to replace problematic terms [1] with alternatives that are appropriate to the particular project and context. The change does not affect the functionality. I purposely removed master_doc from ```doc/conf.py``` , because if it's not specified then the default 'index' is used [2].
[1] https://inclusivenaming.org/word-lists/tier-1/
[2] https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-master_doc

Remove problematic language from the code
