configure.ac
This is a bugfix for issue #16.
=> Fix for "--enable-docs" configure option

tests/Makefile.am
closes https://github.com/rsyslog/liblognorm/issues/27
=> fix make dist problem rooted by output file in EXTRA_DIST

doc/configuration.rst, src/parser.c, src/parser.h, src/samp.c, tests/Makefile.am, tests/field_duration.sh, tests/field_whitespace.sh
=> add new syntaxes

doc/configuration.rst, src/parser.c, src/parser.h, src/samp.c, tests/Makefile.am, tests/field_hexnumber.sh, tests/field_kernel_timestamp.sh
closes https://github.com/rsyslog/liblognorm/issues/34
=> add parser kernel-timestamp

ChangeLog, doc/configuration.rst, src/parser.c, src/parser.h, src/samp.c, tests/Makefile.am, tests/field_json.sh
closes https://github.com/rsyslog/liblognorm/issues/32
=> add new parser "json"

doc/configuration.rst, src/parser.c, src/parser.h, src/samp.c, tests/Makefile.am, tests/field_cee-syslog.sh
closes https://github.com/rsyslog/liblognorm/issues/31
=> add new parser "cee-syslog"

ChangeLog, doc/configuration.rst, src/parser.c, src/parser.h, src/samp.c, tests/Makefile.am, tests/field_mac48.sh
implements https://github.com/rsyslog/liblognorm/issues/46
=> add "mac48" parser for mac layer addresses

src/ptree.c
Code fixing the bug described in issue #66.
=> Fixed bug where an index was being incorrectly casted

doc/configuration.rst, src/parser.c, src/parser.h, src/samp.c, tests/Makefile.am, tests/field_ipv6.sh
closes https://github.com/rsyslog/liblognorm/issues/69
=> add ipv6 parser

src/lognormalizer.c, src/parser.c, src/ptree.c, src/samp.c
... more or less cosmetic, with a very remote chance for a real problem
in loganalyzer tool. Nevertheless, good to fix.
=> fixed some issues detected by clang static analyzer

doc/configuration.rst, src/parser.c
closes https://github.com/rsyslog/liblognorm/issues/68
=> change char-seperated to accept multiple terminator characters

src/pdag.c, src/samp.c, tests/Makefile.am, tests/names.sh
closes https://github.com/rsyslog/liblognorm/issues/104
=> v2: field to be discarded is now identfied by omiting "name" attribute

doc/configuration.rst, tests/Makefile.am, tests/repeat_very_simple.sh
this is a first shot at providing updated doc
closes https://github.com/rsyslog/liblognorm/issues/115
=> v2: update doc to match v2 engine

src/pdag.c
closes https://github.com/rsyslog/liblognorm/issues/118
=> v2: assign default user priority to 30,000 (as documented)

src/pdag.c, tests/Makefile.am, tests/alternative_nested.sh
closes https://github.com/rsyslog/liblognorm/issues/120
=> v2: permit nested array in "alternative" parser

src/parser.c
Note: this fixes a non-released bug
=> fix broken v2 string-to implementation

configure.ac, src/helpers.h, src/json_compatibility.c, src/json_compatibility.h, src/liblognorm.c, src/lognorm.h, src/lognormalizer.c, src/parser.c, src/pdag.c, src/pdag.h, src/v1_parser.c, src/v1_ptree.c, src/v1_ptree.h, src/v1_samp.c, tests/repeat_mismatch_in_while.sh
most importantly also on our way to add backtracking stats
=> Performance (and other) enhancements

doc/configuration.rst, src/pdag.c, tests/Makefile.am, tests/usrdef_ipaddr_dotdot.sh, tests/usrdef_ipaddr_dotdot2.sh, tests/usrdef_ipaddr_dotdot3.sh
useful for custom-defined types, for details see doc patch below.
=> add ".." special name

lognorm.pc.in, src/internal.h, src/liblognorm.h
Small fixes for our public API / pkg-config file
=> Fix pc dependencies

src/samp.c, tests/Makefile.am, tests/annotate.sh, tests/exec.sh
closes https://github.com/rsyslog/liblognorm/issues/225
=> permit inline comments in "annotate" lines

.travis.yml
previous code did not do all necessary updates
=> travis: fix sphinx install

src/Makefile.am, src/liblognorm.c, src/liblognorm.h, src/samp.c, src/samp.h, src/v1_samp.c
introduces new API:
int ln_sampLoadFromString(ln_ctx ctx, const char *string);
=> add ability to load rulebase from a string

.travis.yml, CI/check_codestyle.sh, compat/strndup.c, src/pdag.c, src/samp.c, src/v1_parser.c, src/v1_parser.h, src/v1_ptree.c, src/v1_samp.c, tests/json_eq.c, tools/slsa.c
maintainer edit:
closes https://github.com/rsyslog/liblognorm/pull/205
=> travis: add check for codestyle

tests/Makefile.am, tests/rule_last_str_short.sh
see also https://github.com/rsyslog/liblognorm/pull/246
=> add (short) test for string being last in a rule

tests/Makefile.am, tests/rule_last_str_long.sh
see also https://github.com/rsyslog/liblognorm/pull/246
=> add (long) test for string being last in a rule

doc/configuration.rst, src/parser.c, src/parser.h, src/pdag.c, tests/Makefile.am, tests/field_rfc5424timestamp-fmt_timestamp-unix-ms.sh, tests/field_rfc5424timestamp-fmt_timestamp-unix.sh
=> add ability to reformat RFC timestamps to unix timestamp

doc/configuration.rst, src/parser.c, tests/Makefile.am, tests/exec.sh, tests/field_string_doc_sample_lazy.sh, tests/field_string_lazy_matching.sh
This introduces paramter "matching.lazy".
=> string parser: add "lazy" matching mode

src/parser.c
=> do new ci run on #284

tests/Makefile.am, tests/field_cisco-interface-spec-at-EOL.sh
see also https://github.com/rsyslog/liblognorm/issues/229
=> testbench: add test for cisco-interface-spec parser at end of line

compat/Makefile.am, compat/asprintf.c, src/internal.h, src/lognormalizer.c
Another PR for AIX. Tools are not tested on this OS (I'll do but later)
=> AIX port : added compatibility and modified lognormalizer for AIX.

tests/exec.sh, tests/field_descent.sh, tests/field_descent_with_invalid_ruledef.sh, tests/field_interpret.sh
=> cleanup shell scripting

tests/field_duration_v1.sh, tests/field_float-fmt_number.sh, tests/field_float_v1.sh, tests/field_hexnumber_v1.sh, tests/field_kernel_timestamp_v1.sh, tests/field_recursive.sh, tests/field_regex_default_group_parse_and_return.sh, tests/field_regex_with_consume_group.sh, tests/field_regex_with_consume_group_and_return_group.sh, tests/field_regex_with_negation.sh, tests/field_rest_v1.sh, tests/field_string.sh, tests/field_string_doc_sample_lazy.sh, tests/field_string_lazy_matching.sh, tests/field_string_perm_chars.sh, tests/field_suffixed.sh, tests/field_tokenized.sh, tests/field_tokenized_recursive.sh, tests/field_tokenized_with_regex.sh, tests/field_whitespace.sh, tests/field_whitespace_jsoncnf.sh, tests/field_whitespace_v1.sh, tests/parser_LF.sh, tests/parser_whitespace.sh, tests/rule_last_str_long.sh
=> more cleanup of shell scripting
